# Enable interprocedural (i.e., link time) optimization (IPO/LTO)
macro(modern_cpp_template_enable_ipo)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT result OUTPUT output)
  if(result)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(SEND_ERROR "LTO/IPO is not supported: ${output}")
  endif()
endmacro()
