# Handle the creation of a project based on this template
# This will rename all references of the template name to the project name
# This will remove whatever is not needed

name: Template Cleanup
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop
permissions:
  contents: write

env:
  TEMPLATES_PATH: ".github/template"

jobs:
  template-cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - g++-12
        generator:
          - "Ninja"
        build_type:
          - "Release"
        include:
          - compiler: g++-12
            ccompiler: gcc-12

    steps:
      - uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get install -y gcc-12 g++-12 ninja-build doxygen graphviz texlive-latex-extra libpfm4 ghostscript cmake ccache cppcheck gcovr
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}
